// Generated by scripts/generate-map-colour-scale.ts from map-colour-scale.v1.json. Do not edit.
export const MAP_COLOUR_SCALE_VERSION = "v1" as const;

export const MAP_COLOUR_SCALE = [
  { id: "under-560", maximumPsf: 560, label: "Under $560", colour: "#74c8ba" },
  { id: "560-650", maximumPsf: 650, label: "$560–650", colour: "#d9bb61" },
  { id: "650-745", maximumPsf: 745, label: "$650–745", colour: "#e88858" },
  { id: "745-plus", maximumPsf: null, label: "$745+", colour: "#bc4a45" },
] as const;

export type MapColourBandId = (typeof MAP_COLOUR_SCALE)[number]["id"];
export type MapColourBandCounts = Record<MapColourBandId, number>;

export function classifyMapColourScale(pricePerSqft: number): MapColourBandId {
  for (const band of MAP_COLOUR_SCALE) {
    if (band.maximumPsf === null || pricePerSqft < band.maximumPsf) return band.id;
  }
  throw new Error("Map Colour Scale must include an unbounded final band.");
}

export function emptyMapColourBandCounts(): MapColourBandCounts {
  return Object.fromEntries(MAP_COLOUR_SCALE.map((band) => [band.id, 0])) as MapColourBandCounts;
}
