import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type Band = { id: string; maximumPsf: number | null; label: string; colour: string };
type Scale = { version: string; bands: Band[] };

const root = resolve(import.meta.dirname, "..");
const sourcePath = resolve(root, "src/lib/map-colour-scale.v1.json");
const typescriptPath = resolve(root, "src/lib/map-colour-scale.generated.ts");
const cssPath = resolve(root, "src/app/map-colour-scale.generated.css");
const migrationPath = resolve(root, "supabase/migrations/20260905133000_deepen_map_colour_scale.sql");

function validate(scale: Scale) {
  if (scale.version !== "v1" || scale.bands.length === 0 || scale.bands.at(-1)?.maximumPsf !== null) throw new Error("Map Colour Scale v1 needs a final unbounded band.");
  for (const [index, band] of scale.bands.entries()) {
    if (!band.id || !band.label || !/^#[0-9a-f]{6}$/i.test(band.colour)) throw new Error(`Invalid Map Colour Scale band at position ${index}.`);
    if (band.maximumPsf !== null && (!Number.isFinite(band.maximumPsf) || (index > 0 && band.maximumPsf <= (scale.bands[index - 1].maximumPsf ?? Infinity)))) throw new Error("Map Colour Scale maximums must increase.");
  }
}

function typescript(scale: Scale) {
  const bands = scale.bands.map((band) => `  { id: ${JSON.stringify(band.id)}, maximumPsf: ${band.maximumPsf ?? "null"}, label: ${JSON.stringify(band.label)}, colour: ${JSON.stringify(band.colour)} },`).join("\n");
  return `// Generated by scripts/generate-map-colour-scale.ts from map-colour-scale.v1.json. Do not edit.\nexport const MAP_COLOUR_SCALE_VERSION = ${JSON.stringify(scale.version)} as const;\n\nexport const MAP_COLOUR_SCALE = [\n${bands}\n] as const;\n\nexport type MapColourBandId = (typeof MAP_COLOUR_SCALE)[number]["id"];\nexport type MapColourBandCounts = Record<MapColourBandId, number>;\n\nexport function classifyMapColourScale(pricePerSqft: number): MapColourBandId {\n  for (const band of MAP_COLOUR_SCALE) {\n    if (band.maximumPsf === null || pricePerSqft < band.maximumPsf) return band.id;\n  }\n  throw new Error("Map Colour Scale must include an unbounded final band.");\n}\n\nexport function emptyMapColourBandCounts(): MapColourBandCounts {\n  return Object.fromEntries(MAP_COLOUR_SCALE.map((band) => [band.id, 0])) as MapColourBandCounts;\n}\n`;
}

function sqlCase(scale: Scale) {
  return scale.bands.map((band) => band.maximumPsf === null ? `      else '${band.id}'` : `      when p_price_per_sqft < ${band.maximumPsf} then '${band.id}'`).join("\n");
}

function css(scale: Scale) {
  return `/* Generated by scripts/generate-map-colour-scale.ts from src/lib/map-colour-scale.v1.json. Do not edit. */\n${scale.bands.map((band) => `.map-colour-scale-${band.id} { background: ${band.colour}; }`).join("\n")}\n`;
}

function sqlCounts(scale: Scale) {
  return scale.bands.map((band) => `      '${band.id}', count(*) filter (where filtered.price_band = '${band.id}')::integer`).join(",\n");
}

function unversionedMigration(scale: Scale) {
  return `-- Generated by scripts/generate-map-colour-scale.ts from src/lib/map-colour-scale.v1.json. Do not edit.\ncreate or replace function public.map_colour_scale_band_v1(p_price_per_sqft numeric)\nreturns text\nlanguage sql\nimmutable\nstrict\nsecurity invoker\nset search_path = public\nas $$\n  select case\n${sqlCase(scale)}\n    end;\n$$;\n\nrevoke execute on function public.map_colour_scale_band_v1(numeric) from public, anon, authenticated;\ngrant execute on function public.map_colour_scale_band_v1(numeric) to service_role;\n\ncreate or replace function public.get_hdb_map_markers(\n  p_south numeric,\n  p_west numeric,\n  p_north numeric,\n  p_east numeric,\n  p_zoom integer,\n  p_flat_type text default 'all',\n  p_price_band text default 'any',\n  p_lease_band text default 'any',\n  p_reference_year integer default extract(year from current_date)::integer\n)\nreturns table (\n  marker_kind text, marker_id text, latitude numeric, longitude numeric, block text, street_name text, town text, flat_type text, median_psm numeric, median_price numeric, transaction_count integer, cluster_count integer, price_band_counts jsonb\n)\nlanguage sql\nsecurity invoker\nset search_path = public\nstable\nas $$\n  with settings as (\n    select case when p_zoom <= 11 then 0.03::numeric when p_zoom <= 13 then 0.012::numeric when p_zoom <= 14 then 0.004::numeric else null end as cell_size\n  ), filtered as (\n    select summary.*, summary.median_psm * 0.09290304 as median_psf, public.map_colour_scale_band_v1(summary.median_psm * 0.09290304) as price_band\n    from public.hdb_block_summaries summary\n    where summary.latitude between p_south and p_north and summary.longitude between p_west and p_east\n      and (p_flat_type = 'all' or summary.flat_type = p_flat_type)\n      and (p_price_band = 'any' or (p_price_band = 'under-650' and summary.median_price < 650000) or (p_price_band = '650-850' and summary.median_price >= 650000 and summary.median_price < 850000) or (p_price_band = '850-plus' and summary.median_price >= 850000))\n      and (p_lease_band = 'any' or (p_lease_band = '80-plus' and 99 - (p_reference_year - summary.median_lease_commence_year) >= 80) or (p_lease_band = '70-79' and 99 - (p_reference_year - summary.median_lease_commence_year) between 70 and 79) or (p_lease_band = '60-69' and 99 - (p_reference_year - summary.median_lease_commence_year) between 60 and 69) or (p_lease_band = 'under-60' and 99 - (p_reference_year - summary.median_lease_commence_year) < 60))\n  ), clusters as (\n    select floor(filtered.latitude / settings.cell_size) * settings.cell_size as cell_latitude, floor(filtered.longitude / settings.cell_size) * settings.cell_size as cell_longitude, avg(filtered.latitude) as latitude, avg(filtered.longitude) as longitude, count(*)::integer as cluster_count, jsonb_build_object(\n${sqlCounts(scale)}\n    ) as price_band_counts\n    from filtered cross join settings where settings.cell_size is not null\n    group by cell_latitude, cell_longitude\n  )\n  select 'cluster'::text, concat('cluster:', cell_latitude, ':', cell_longitude), clusters.latitude, clusters.longitude, null::text, null::text, null::text, null::text, null::numeric, null::numeric, null::integer, clusters.cluster_count, clusters.price_band_counts from clusters\n  union all\n  select 'block'::text, filtered.block_id, filtered.latitude, filtered.longitude, filtered.block, filtered.street_name, filtered.town, filtered.flat_type, filtered.median_psm, filtered.median_price, filtered.transaction_count, null::integer, null::jsonb from filtered cross join settings where settings.cell_size is null;\n$$;\n\nrevoke execute on function public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer) from public, anon, authenticated;\ngrant execute on function public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer) to service_role;\n`;
}

function migration(scale: Scale) {
  return unversionedMigration(scale).replace(
    "\n\ncreate or replace function public.get_hdb_map_markers(",
    "\n\n-- The return table changes from threshold-shaped columns to one stable-ID object.\n-- PostgreSQL cannot replace a function while changing its return type.\ndrop function if exists public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer);\n\ncreate function public.get_hdb_map_markers("
  );
}

async function main() {
  const scale = JSON.parse(await readFile(sourcePath, "utf8")) as Scale;
  validate(scale);
  const outputs = new Map([[typescriptPath, typescript(scale)], [cssPath, css(scale)], [migrationPath, migration(scale)]]);
  if (process.argv.includes("--check")) {
    for (const [path, expected] of outputs) if (await readFile(path, "utf8") !== expected) throw new Error(`${path} is stale; run pnpm generate:map-colour-scale.`);
    return;
  }
  await Promise.all([...outputs].map(([path, content]) => writeFile(path, content)));
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
