-- Generated by scripts/generate-map-colour-scale.ts from src/lib/map-colour-scale.v1.json. Do not edit.
create or replace function public.map_colour_scale_band_v1(p_price_per_sqft numeric)
returns text
language sql
immutable
strict
security invoker
set search_path = public
as $$
  select case
      when p_price_per_sqft < 560 then 'under-560'
      when p_price_per_sqft < 650 then '560-650'
      when p_price_per_sqft < 745 then '650-745'
      else '745-plus'
    end;
$$;

revoke execute on function public.map_colour_scale_band_v1(numeric) from public, anon, authenticated;
grant execute on function public.map_colour_scale_band_v1(numeric) to service_role;

-- The return table changes from threshold-shaped columns to one stable-ID object.
-- PostgreSQL cannot replace a function while changing its return type.
drop function if exists public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer);

create function public.get_hdb_map_markers(
  p_south numeric,
  p_west numeric,
  p_north numeric,
  p_east numeric,
  p_zoom integer,
  p_flat_type text default 'all',
  p_price_band text default 'any',
  p_lease_band text default 'any',
  p_reference_year integer default extract(year from current_date)::integer
)
returns table (
  marker_kind text, marker_id text, latitude numeric, longitude numeric, block text, street_name text, town text, flat_type text, median_psm numeric, median_price numeric, transaction_count integer, cluster_count integer, price_band_counts jsonb
)
language sql
security invoker
set search_path = public
stable
as $$
  with settings as (
    select case when p_zoom <= 11 then 0.03::numeric when p_zoom <= 13 then 0.012::numeric when p_zoom <= 14 then 0.004::numeric else null end as cell_size
  ), filtered as (
    select summary.*, summary.median_psm * 0.09290304 as median_psf, public.map_colour_scale_band_v1(summary.median_psm * 0.09290304) as price_band
    from public.hdb_block_summaries summary
    where summary.latitude between p_south and p_north and summary.longitude between p_west and p_east
      and (p_flat_type = 'all' or summary.flat_type = p_flat_type)
      and (p_price_band = 'any' or (p_price_band = 'under-650' and summary.median_price < 650000) or (p_price_band = '650-850' and summary.median_price >= 650000 and summary.median_price < 850000) or (p_price_band = '850-plus' and summary.median_price >= 850000))
      and (p_lease_band = 'any' or (p_lease_band = '80-plus' and 99 - (p_reference_year - summary.median_lease_commence_year) >= 80) or (p_lease_band = '70-79' and 99 - (p_reference_year - summary.median_lease_commence_year) between 70 and 79) or (p_lease_band = '60-69' and 99 - (p_reference_year - summary.median_lease_commence_year) between 60 and 69) or (p_lease_band = 'under-60' and 99 - (p_reference_year - summary.median_lease_commence_year) < 60))
  ), clusters as (
    select floor(filtered.latitude / settings.cell_size) * settings.cell_size as cell_latitude, floor(filtered.longitude / settings.cell_size) * settings.cell_size as cell_longitude, avg(filtered.latitude) as latitude, avg(filtered.longitude) as longitude, count(*)::integer as cluster_count, jsonb_build_object(
      'under-560', count(*) filter (where filtered.price_band = 'under-560')::integer,
      '560-650', count(*) filter (where filtered.price_band = '560-650')::integer,
      '650-745', count(*) filter (where filtered.price_band = '650-745')::integer,
      '745-plus', count(*) filter (where filtered.price_band = '745-plus')::integer
    ) as price_band_counts
    from filtered cross join settings where settings.cell_size is not null
    group by cell_latitude, cell_longitude
  )
  select 'cluster'::text, concat('cluster:', cell_latitude, ':', cell_longitude), clusters.latitude, clusters.longitude, null::text, null::text, null::text, null::text, null::numeric, null::numeric, null::integer, clusters.cluster_count, clusters.price_band_counts from clusters
  union all
  select 'block'::text, filtered.block_id, filtered.latitude, filtered.longitude, filtered.block, filtered.street_name, filtered.town, filtered.flat_type, filtered.median_psm, filtered.median_price, filtered.transaction_count, null::integer, null::jsonb from filtered cross join settings where settings.cell_size is null;
$$;

revoke execute on function public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer) from public, anon, authenticated;
grant execute on function public.get_hdb_map_markers(numeric, numeric, numeric, numeric, integer, text, text, text, integer) to service_role;
